name: Checkmarx Security Scan
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  build:
    name: Checkmarx Security Scan
    runs-on: ubuntu-latest
    if: github.base_ref == github.event.repository.default_branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check changed files
        uses: tj-actions/changed-files@v43
        id: changedfiles
      
      - name: Checkmarx - Scan Execution (Results)
        uses: grupo-sbf/checkmarx-action@main
        with:
          project_name: ${{ github.repository }}
          github_token: ${{ secrets.CX_GITHUB_TOKEN }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri:  ${{ secrets.CX_BASE_URI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          changed_files: ${{ steps.changedfiles.outputs.all }}
